---
# Assumes 64 bit Linux
- name: Install the MySQL client library
  yum:
    name: mysql

- name: User account for Google Cloud SQL proxy
  user:
    name: gcsql_proxy
    system: true
    createhome: false

- name: Download Google Cloud SQL Proxy
  get_url:
    dest: /usr/local/bin/cloud_sql_proxy
    url: https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
    mode: u+x
    owner: gcsql_proxy

- name: systemd unit for Google Cloud SQL proxy
  template:
    src: usr/lib/systemd/system/gcsql_proxy.service
    dest: /usr/lib/systemd/system/

- name: Start the systemd unit
  systemd:
    daemon_reload: true
    state: started
    enabled: true
    name: gcsql_proxy
  when: gcsql_proxy_start_service

- name: Enable the systemd unit
  systemd:
    enabled: true
    name: gcsql_proxy
